### ISSUE TITLE
How can I retrieve records by "_id" value?

### ISSUE THREAD

**Issue by DoQuangKhai** [iPlantCollaborativeOpenSource/Robotframework-MongoDB-Library#6]
I have a record in mongoDB:
`{
    "_id" : ObjectId("51d17a4fd2d9c16268000000"),
    "date" : "20141205"
}`

I want to get this record by using `"Retrieve Mongodb Records With Desired Fields"` to return the record. I could get the record with `"date"` field by `{"date":"20141205"}`, but with `"_id"` this keyword did not work.
I tried with many Json syntax:
`{"_id":"51d17a4fd2d9c16268000000"}`
RETURN: `${records} = <NULL>` 

`{"_id":"ObjectId('54c1a1efa23def8152000006')"}`
RETURN: `${records} = <NULL> `

`{"_id":ObjectId("54c1a1efa23def8152000006")}`
RETURN: `ValueError: No JSON object could be decoded`
...
How can I get the record by `"_id"` value?
Thanks in advance.

**Comment by jerry57** [comment]
As it turns out, mongo does not allow searching globally on ObjectIDs.  You can only search one field by using something like:
{ "routines._id": ObjectID("51d17a4fd2d9c16268000000") }

If you can come up with a better way of doing this, please feel free to do a pull request.

**Comment by DoQuangKhai** [comment]
Hi jerry57.
I have found that I can use 2 other fields to return the record.
Thanks for the reply.

**Comment by yair26g** [comment]
Any Idea of How to get a record by ObjectId?
As DoQuangKhai wrote, i keep getting NULL.

**Comment by jerry57** [comment]
As stated above, Mongo does not allow searching on _id.  You retrieve a specific ObjectID.  You can get ObjectID returned by searching for other keys and then using it.  unfortunately there is nothing the library can do right now to resolve this issue.
