### ISSUE TITLE
Cannot Connect to Mongo

### ISSUE THREAD

**Issue by trogdor259** [iPlantCollaborativeOpenSource/Robotframework-MongoDB-Library#7]
I have a very simple test created in robot framework to connect to my mongo server. When I run it I get the message:
AttributeError: 'module' object has no attribute 'connection'
I am using python 2.7.6 and pymongo 3.0.2.
Is there a dependency I am missing or is this incompatible with the newest versions of python and pymongo?

**Comment by jerry57** [comment]
Not that I am aware of.  Have you tried an earlier version of pymongo (before 3.0)?  The projects here have dropped support/usage of MongoDB, so I have not been working with it or keeping up.

**Comment by trogdor259** [comment]
I changed to using pymongo 2.8 and it works. So the issue is definitely with the version of pymongo being used

**Comment by jerry57** [comment]
Sounds like they changed something in the connection string.  Can you continue to use 2.8 for now and I will take a look when I get a break.  Hopefully sometime this week

**Comment by trogdor259** [comment]
I will do so. Thanks!

**Comment by EastAnt** [comment]
This library is based on Pymongo 2.2. For version 3.0, something changed and it can work now.
References:
+ PyMongo 2.2 Documentation - http://api.mongodb.org/python/2.2/
And there are some new method that  this library does not contain.

**Comment by jerry57** [comment]
MongoDB-Library now compatible with pymongo 3.0.3 and documentation has been updated.
